<?binding.jca FetchOSBXRefs_db.jca?><wsdl:definitions name="FetchOSBXRefs" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDMApplication/MDMTransformationProject/FetchOSBXRefs" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/FetchOSBXRefs" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MDMApplication/MDMTransformationProject/FetchOSBXRefs" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="FetchOSBXRefs_plt">
        <plt:role name="FetchOSBXRefs_role">
            <plt:portType name="tns:FetchOSBXRefs_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/FetchOSBXRefs" schemaLocation="../xsd/FetchOSBXRefs_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="FetchOSBXRefs_ptt">
        <wsdl:operation name="FetchOSBXRefs">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>