<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="DataBridge.InDynamicWS" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
	<wsdl:types>
		<xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:import namespace="http://schemas.datacontract.org/2004/07/TOPCustomerSite"/>
			<xs:element name="CustomerSite">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="Customers" nillable="true" type="q1:ArrayOfCustomer" xmlns:q1="http://schemas.datacontract.org/2004/07/TOPCustomerSite"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CustomerSiteResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="CustomerSiteResult" nillable="true" type="q2:Response" xmlns:q2="http://schemas.datacontract.org/2004/07/TOPCustomerSite"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
		<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
			<xs:element name="anyType" nillable="true" type="xs:anyType"/>
			<xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
			<xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
			<xs:element name="boolean" nillable="true" type="xs:boolean"/>
			<xs:element name="byte" nillable="true" type="xs:byte"/>
			<xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
			<xs:element name="decimal" nillable="true" type="xs:decimal"/>
			<xs:element name="double" nillable="true" type="xs:double"/>
			<xs:element name="float" nillable="true" type="xs:float"/>
			<xs:element name="int" nillable="true" type="xs:int"/>
			<xs:element name="long" nillable="true" type="xs:long"/>
			<xs:element name="QName" nillable="true" type="xs:QName"/>
			<xs:element name="short" nillable="true" type="xs:short"/>
			<xs:element name="string" nillable="true" type="xs:string"/>
			<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
			<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
			<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
			<xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
			<xs:element name="char" nillable="true" type="tns:char"/>
			<xs:simpleType name="char">
				<xs:restriction base="xs:int"/>
			</xs:simpleType>
			<xs:element name="duration" nillable="true" type="tns:duration"/>
			<xs:simpleType name="duration">
				<xs:restriction base="xs:duration">
					<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
					<xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
					<xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="guid" nillable="true" type="tns:guid"/>
			<xs:simpleType name="guid">
				<xs:restriction base="xs:string">
					<xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:attribute name="FactoryType" type="xs:QName"/>
			<xs:attribute name="Id" type="xs:ID"/>
			<xs:attribute name="Ref" type="xs:IDREF"/>
		</xs:schema>
		<xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/TOPCustomerSite" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/TOPCustomerSite">
			<xs:complexType name="ArrayOfCustomer">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Customer" nillable="true" type="tns:Customer"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfCustomer" nillable="true" type="tns:ArrayOfCustomer"/>
			<xs:complexType name="Customer">
				<xs:sequence>
					<xs:element name="Address" nillable="true" type="tns:Address"/>
					<xs:element name="ContactInformation" nillable="true" type="tns:ContactInformation"/>
					<xs:element minOccurs="0" name="ID" nillable="true" type="xs:string"/>
					<xs:element name="Inactive" type="xs:boolean"/>
					<xs:element name="Name" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="SchedulingGroup" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Sites" nillable="true" type="tns:ArrayOfSite"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Customer" nillable="true" type="tns:Customer"/>
			<xs:complexType name="Address">
				<xs:sequence>
					<xs:element minOccurs="0" name="County" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="HouseNumber" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Latitude" type="xs:double"/>
					<xs:element minOccurs="0" name="Longitude" type="xs:double"/>
					<xs:element name="Postcode" nillable="true" type="xs:string"/>
					<xs:element name="StreetName" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Town" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Address" nillable="true" type="tns:Address"/>
			<xs:complexType name="ContactInformation">
				<xs:sequence>
					<xs:element minOccurs="0" name="ContactName" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Email" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="PhoneNumber" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ContactInformation" nillable="true" type="tns:ContactInformation"/>
			<xs:complexType name="ArrayOfSite">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Site" nillable="true" type="tns:Site"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfSite" nillable="true" type="tns:ArrayOfSite"/>
			<xs:complexType name="Site">
				<xs:sequence>
					<xs:element name="Address" nillable="true" type="tns:Address"/>
					<xs:element minOccurs="0" name="ClosingTime" nillable="true" type="xs:string"/>
					<xs:element name="ContactInformation" nillable="true" type="tns:ContactInformation"/>
					<xs:element minOccurs="0" name="DayNameAvailability" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="ID" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Inactive" type="xs:boolean"/>
					<xs:element name="Name" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Notes" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="OpeningTime" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="OrderType" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="Terminals" nillable="true" type="tns:ArrayOfTerminal"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Site" nillable="true" type="tns:Site"/>
			<xs:complexType name="ArrayOfTerminal">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Terminal" nillable="true" type="tns:Terminal"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfTerminal" nillable="true" type="tns:ArrayOfTerminal"/>
			<xs:complexType name="Terminal">
				<xs:sequence>
					<xs:element minOccurs="0" name="ID" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Terminal" nillable="true" type="tns:Terminal"/>
			<xs:complexType name="Response">
				<xs:sequence>
					<xs:element minOccurs="0" name="Customers" nillable="true" type="tns:ArrayOfResponseCustomer"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Response" nillable="true" type="tns:Response"/>
			<xs:complexType name="ArrayOfResponseCustomer">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="ResponseCustomer" nillable="true" type="tns:ResponseCustomer"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfResponseCustomer" nillable="true" type="tns:ArrayOfResponseCustomer"/>
			<xs:complexType name="ResponseCustomer">
				<xs:sequence>
					<xs:element minOccurs="0" name="Description" nillable="true" type="xs:string"/>
					<xs:element name="ID" nillable="true" type="xs:string"/>
					<xs:element name="Status" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ResponseCustomer" nillable="true" type="tns:ResponseCustomer"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="CustomerSite_CustomerSite_InputMessage">
		<wsdl:part name="parameters" element="tns:CustomerSite"/>
	</wsdl:message>
	<wsdl:message name="CustomerSite_CustomerSite_OutputMessage">
		<wsdl:part name="parameters" element="tns:CustomerSiteResponse"/>
	</wsdl:message>
	<wsdl:portType name="CustomerSite">
		<wsdl:operation name="CustomerSite">
			<wsdl:input wsaw:Action="http://tempuri.org/CustomerSite/CustomerSite" message="tns:CustomerSite_CustomerSite_InputMessage"/>
			<wsdl:output wsaw:Action="http://tempuri.org/CustomerSite/CustomerSiteResponse" message="tns:CustomerSite_CustomerSite_OutputMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BasicHttpBinding_CustomerSite" type="tns:CustomerSite">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CustomerSite">
			<soap:operation soapAction="http://tempuri.org/CustomerSite/CustomerSite" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DataBridge.InDynamicWS">
		<wsdl:port name="BasicHttpBinding_CustomerSite" binding="tns:BasicHttpBinding_CustomerSite">
			<soap:address location="http://gry75app02.greenergy.gateway:8000/TOP_CustomerSite.svc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>